package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.AuthoritiesRepository;
import mobileoffice.dao.entities.Authorities;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface AuthoritiesDataService extends DataService<AuthoritiesRepository,Authorities> {
}