package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.ClientRepository;
import mobileoffice.dao.entities.Client;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface ClientDataService extends DataService<ClientRepository,Client> {
}