package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.ClientContractRspRepository;
import mobileoffice.dao.entities.ClientContractRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface ClientContractRspDataService extends DataService<ClientContractRspRepository,ClientContractRsp> {
}