package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.ContractOptionRspRepository;
import mobileoffice.dao.entities.ContractOptionRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface ContractOptionRspDataService extends DataService<ContractOptionRspRepository,ContractOptionRsp> {
}