package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.ContractRepository;
import mobileoffice.dao.entities.Contract;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface ContractDataService extends DataService<ContractRepository,Contract> {
}