package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.ManagerRepository;
import mobileoffice.dao.entities.Manager;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface ManagerDataService extends DataService<ManagerRepository,Manager> {
}