package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.NewviewRepository;
import mobileoffice.dao.entities.Newview;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface NewviewDataService extends DataService<NewviewRepository,Newview> {
}