package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.OptionRelationsRspRepository;
import mobileoffice.dao.entities.OptionRelationsRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface OptionRelationsRspDataService extends DataService<OptionRelationsRspRepository,OptionRelationsRsp> {
}