package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.OptionsRepository;
import mobileoffice.dao.entities.Options;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface OptionsDataService extends DataService<OptionsRepository,Options> {
}