package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.TariffRepository;
import mobileoffice.dao.entities.Tariff;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface TariffDataService extends DataService<TariffRepository,Tariff> {
}