package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.TariffOptionsRspRepository;
import mobileoffice.dao.entities.TariffOptionsRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface TariffOptionsRspDataService extends DataService<TariffOptionsRspRepository,TariffOptionsRsp> {
}