package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.TariffTariffOptionRepository;
import mobileoffice.dao.entities.TariffTariffOption;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface TariffTariffOptionDataService extends DataService<TariffTariffOptionRepository,TariffTariffOption> {
}