package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.TariffOptionRspRepository;
import mobileoffice.dao.entities.TariffOptionRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface TariffOptionRspDataService extends DataService<TariffOptionRspRepository,TariffOptionRsp> {
}