package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.UsersRepository;
import mobileoffice.dao.entities.Users;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface UsersDataService extends DataService<UsersRepository,Users> {
}