package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.VContractWithTariffRepository;
import mobileoffice.dao.entities.VContractWithTariff;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface VContractWithTariffDataService extends DataService<VContractWithTariffRepository,VContractWithTariff> {
}