package mobileoffice.business.contracts.data;;

import base.business.contracts.DataService;
import mobileoffice.dao.contracts.VTariffWithOptionsRepository;
import mobileoffice.dao.entities.VTariffWithOptions;

/*
    !!!! AUTOGENERATED !!!!!
*/
public interface VTariffWithOptionsDataService extends DataService<VTariffWithOptionsRepository,VTariffWithOptions> {
}