package ${settings.entityPackageName};

import base.dao.contracts.HasLongId;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class ${model.className} implements HasLongId, Serializable {
    public ${model.className}() { }
    <#list model.columns as column>
    private ${column.dataType} ${column.codeName};
    </#list>
    <#list model.foreignKeys as key>
    <#if key.isOneToMany()>
    private Collection<${key.table.className}> ${key.keyColumnName};
    </#if>
    <#if !key.isOneToMany()>
    private ${key.table.className} ${key.keyColumnName};
    </#if>
    </#list>

    <#list model.columns as column>
    public ${column.dataType} get${column.className}(){
        return this.${column.codeName};
    }

    public void set${column.className} (${column.dataType} ${column.codeName}) {
        this.${column.codeName} = ${column.codeName};
    }
    </#list>
    <#list model.foreignKeys as key>
        <#if key.isOneToMany()>
    @JsonIgnore
    public Collection<${key.table.className}> get${key.keyColumnNameForProperties}(){
        return this.${key.keyColumnName};
    }

    public void set${key.keyColumnNameForProperties} (Collection<${key.table.className}> ${key.keyColumnName}) {
        this.${key.keyColumnName} = ${key.keyColumnName};
    }
        </#if>
        <#if !key.isOneToMany()>
    @JsonIgnore
    public ${key.table.className} get${key.keyColumnNameForProperties}(){
        return this.${key.keyColumnName};
    }

    public void set${key.keyColumnNameForProperties} (${key.table.className} ${key.keyColumnName}) {
        this.${key.keyColumnName} = ${key.keyColumnName};
    }
        </#if>
    </#list>
}