<hibernate-mapping>
    <!-- !!!!! AUTOGENERATED !!!!!! -->
    <class name="${settings.entityPackageName}.${model.className}" table="${model.name}" schema="${model.schemaName}">
        <#list model.columns as column><#if column.isPrimaryKey()>
        <id name="${column.codeName}" column="${column.name}">
            <#if column.autoIncrement><generator class="identity"/></#if>
        </id>
        </#if></#list>
        <#list model.columns as column>
        <#if !column.isPrimaryKey()><property name="${column.codeName}" column="${column.name}"/></#if>
        </#list>
        <#list model.foreignKeys as key>
        <#if key.isOneToMany()>
        <set name="${key.keyColumnName}" inverse="true">
            <key>
                <column name="${key.column.name}"/>
            </key>
            <one-to-many not-found="ignore" class="${settings.entityPackageName}.${key.table.className}"/>
         </set>
        </#if>
        <#if !key.isOneToMany()>
            <many-to-one name="${key.keyColumnName}" insert="false" update="false" not-found="ignore" class="${settings.entityPackageName}.${key.table.className}">
                <column name="${key.refColumn.name}"/>
            </many-to-one>
        </#if>
       </#list>
    </class>
</hibernate-mapping>