package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Authorities;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface AuthoritiesRepository extends Repository<Authorities> {
}