package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Client;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface ClientRepository extends Repository<Client> {
}