package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.ClientContractRsp;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface ClientContractRspRepository extends Repository<ClientContractRsp> {
}