package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.ContractOptionRsp;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface ContractOptionRspRepository extends Repository<ContractOptionRsp> {
}