package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Contract;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface ContractRepository extends Repository<Contract> {
}