package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Manager;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface ManagerRepository extends Repository<Manager> {
}