package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Newview;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface NewviewRepository extends Repository<Newview> {
}