package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.OptionRelationsRsp;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface OptionRelationsRspRepository extends Repository<OptionRelationsRsp> {
}