package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Options;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface OptionsRepository extends Repository<Options> {
}