package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.TariffTariffOption;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface TariffTariffOptionRepository extends Repository<TariffTariffOption> {
}