package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.TariffOptionsRsp;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface TariffOptionsRspRepository extends Repository<TariffOptionsRsp> {
}