package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Tariff;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface TariffRepository extends Repository<Tariff> {
}