package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.TariffOptionRsp;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface TariffOptionRspRepository extends Repository<TariffOptionRsp> {
}