package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.Users;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface UsersRepository extends Repository<Users> {
}