package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.VContractWithTariff;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface VContractWithTariffRepository extends Repository<VContractWithTariff> {
}