package mobileoffice.dao.contracts;

import base.dao.contracts.Repository;
import mobileoffice.dao.entities.VTariffWithOptions;

/*
!!!! AUTOGENERATED !!!!!
*/
public interface VTariffWithOptionsRepository extends Repository<VTariffWithOptions> {
}