package ${settings.dataServicesPackageName};

import base.business.services.DataServiceImpl;
import ${settings.dataServiceInterfacesPackageName}.${model.className}DataService;
import ${settings.repositoryInterfacePackageName}.${model.className}Repository;
import ${settings.entityPackageName}.${model.className};

/*
    !!!! AUTOGENERATED !!!!!
*/
public class ${model.className}DataServiceImpl extends DataServiceImpl<${model.className}Repository, ${model.className}> implements ${model.className}DataService {
public ${model.className}DataServiceImpl(${model.className}Repository repository) {
    super(repository);
    }
}