package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Authorities;
import mobileoffice.dao.contracts.AuthoritiesRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class AuthoritiesRepositoryImpl extends RepositoryImpl<Authorities> implements AuthoritiesRepository{
    public AuthoritiesRepositoryImpl() {
     super(Authorities.class);
    }
}