package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.ClientContractRsp;
import mobileoffice.dao.contracts.ClientContractRspRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class ClientContractRspRepositoryImpl extends RepositoryImpl<ClientContractRsp> implements ClientContractRspRepository{
    public ClientContractRspRepositoryImpl() {
     super(ClientContractRsp.class);
    }
}