package mobileoffice.dao.repositories;

import org.hibernate.SessionFactory;
import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Contract;
import mobileoffice.dao.contracts.ContractRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class ContractRepositoryImpl extends RepositoryImpl<Contract> implements ContractRepository{
    public ContractRepositoryImpl(SessionFactory sessionFactory){
     super(sessionFactory, Contract.class);
    }
}