package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.ContractOptionRsp;
import mobileoffice.dao.contracts.ContractOptionRspRepository;
import org.hibernate.SessionFactory;

/*
!!!! AUTOGENERATED !!!!!
*/
public class ContractOptionRspRepositoryImpl extends RepositoryImpl<ContractOptionRsp> implements ContractOptionRspRepository{
    public ContractOptionRspRepositoryImpl() {
     super(ContractOptionRsp.class);
    }
}