package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Contract;
import mobileoffice.dao.contracts.ContractRepository;
import org.hibernate.SessionFactory;

/*
!!!! AUTOGENERATED !!!!!
*/
public class ContractRepositoryImpl extends RepositoryImpl<Contract> implements ContractRepository{
    public ContractRepositoryImpl() {
     super(Contract.class);
    }
}