package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Manager;
import mobileoffice.dao.contracts.ManagerRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class ManagerRepositoryImpl extends RepositoryImpl<Manager> implements ManagerRepository{
    public ManagerRepositoryImpl() {
     super(Manager.class);
    }
}