package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Newview;
import mobileoffice.dao.contracts.NewviewRepository;
import org.hibernate.SessionFactory;

/*
!!!! AUTOGENERATED !!!!!
*/
public class NewviewRepositoryImpl extends RepositoryImpl<Newview> implements NewviewRepository{
    public NewviewRepositoryImpl() {
     super(Newview.class);
    }
}