package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.OptionRelationsRsp;
import mobileoffice.dao.contracts.OptionRelationsRspRepository;
import org.hibernate.SessionFactory;

/*
!!!! AUTOGENERATED !!!!!
*/
public class OptionRelationsRspRepositoryImpl extends RepositoryImpl<OptionRelationsRsp> implements OptionRelationsRspRepository{
    public OptionRelationsRspRepositoryImpl() {
     super(OptionRelationsRsp.class);
    }
}