package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Options;
import mobileoffice.dao.contracts.OptionsRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class OptionsRepositoryImpl extends RepositoryImpl<Options> implements OptionsRepository{
    public OptionsRepositoryImpl() {
     super(Options.class);
    }
}