package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Tariff;
import mobileoffice.dao.contracts.TariffRepository;
import org.hibernate.SessionFactory;

/*
!!!! AUTOGENERATED !!!!!
*/
public class TariffRepositoryImpl extends RepositoryImpl<Tariff> implements TariffRepository{
    public TariffRepositoryImpl() {
     super(Tariff.class);
    }
}