package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.TariffOptionsRsp;
import mobileoffice.dao.contracts.TariffOptionsRspRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class TariffOptionsRspRepositoryImpl extends RepositoryImpl<TariffOptionsRsp> implements TariffOptionsRspRepository{
    public TariffOptionsRspRepositoryImpl() {
     super(TariffOptionsRsp.class);
    }
}