package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.Users;
import mobileoffice.dao.contracts.UsersRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class UsersRepositoryImpl extends RepositoryImpl<Users> implements UsersRepository{
    public UsersRepositoryImpl() {
     super(Users.class);
    }
}