package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.VContractWithTariff;
import mobileoffice.dao.contracts.VContractWithTariffRepository;
import org.hibernate.SessionFactory;

/*
!!!! AUTOGENERATED !!!!!
*/
public class VContractWithTariffRepositoryImpl extends RepositoryImpl<VContractWithTariff> implements VContractWithTariffRepository{
    public VContractWithTariffRepositoryImpl() {
     super(VContractWithTariff.class);
    }
}