package mobileoffice.dao.repositories;

import base.dao.repositories.RepositoryImpl;
import mobileoffice.dao.entities.VTariffWithOptions;
import mobileoffice.dao.contracts.VTariffWithOptionsRepository;

/*
!!!! AUTOGENERATED !!!!!
*/
public class VTariffWithOptionsRepositoryImpl extends RepositoryImpl<VTariffWithOptions> implements VTariffWithOptionsRepository{
    public VTariffWithOptionsRepositoryImpl() {
     super(VTariffWithOptions.class);
    }
}