package mobileoffice.utils;

import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class HibernateUtil {
    private static final SessionFactory sessionFactory;
    static {
        try {
            Configuration cfg = new Configuration().configure("hibernate/hibernate.cfg.xml");
            cfg.addResource("hibernate/Client.hbm.xml");
            cfg.addResource("hibernate/ClientContractRsp.hbm.xml");
            cfg.addResource("hibernate/Contract.hbm.xml");
            cfg.addResource("hibernate/Tariff.hbm.xml");
            cfg.addResource("hibernate/TariffOptionRsp.hbm.xml");
            cfg.addResource("hibernate/TariffTariffOption.hbm.xml");
            sessionFactory = cfg.buildSessionFactory();
        } catch (Throwable ex) {
            throw new ExceptionInInitializerError(ex);
        }
    }

    public static SessionFactory getSessionFactory() {
        return sessionFactory;
    }
}
