package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.AuthoritiesDataService;
import mobileoffice.dao.contracts.AuthoritiesRepository;
import mobileoffice.dao.entities.Authorities;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class AuthoritiesDataServiceImpl extends DataServiceImpl<AuthoritiesRepository, Authorities> implements AuthoritiesDataService {
public AuthoritiesDataServiceImpl(AuthoritiesRepository repository) {
    super(repository);
    }
}