package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.ClientContractRspDataService;
import mobileoffice.dao.contracts.ClientContractRspRepository;
import mobileoffice.dao.entities.ClientContractRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class ClientContractRspDataServiceImpl extends DataServiceImpl<ClientContractRspRepository, ClientContractRsp> implements ClientContractRspDataService {
public ClientContractRspDataServiceImpl(ClientContractRspRepository repository) {
    super(repository);
    }
}