package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.ContractOptionRspDataService;
import mobileoffice.dao.contracts.ContractOptionRspRepository;
import mobileoffice.dao.entities.ContractOptionRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class ContractOptionRspDataServiceImpl extends DataServiceImpl<ContractOptionRspRepository, ContractOptionRsp> implements ContractOptionRspDataService {
public ContractOptionRspDataServiceImpl(ContractOptionRspRepository repository) {
    super(repository);
    }
}