package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.NewviewDataService;
import mobileoffice.dao.contracts.NewviewRepository;
import mobileoffice.dao.entities.Newview;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class NewviewDataServiceImpl extends DataServiceImpl<NewviewRepository, Newview> implements NewviewDataService {
public NewviewDataServiceImpl(NewviewRepository repository) {
    super(repository);
    }
}