package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.OptionRelationsRspDataService;
import mobileoffice.dao.contracts.OptionRelationsRspRepository;
import mobileoffice.dao.entities.OptionRelationsRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class OptionRelationsRspDataServiceImpl extends DataServiceImpl<OptionRelationsRspRepository, OptionRelationsRsp> implements OptionRelationsRspDataService {
public OptionRelationsRspDataServiceImpl(OptionRelationsRspRepository repository) {
    super(repository);
    }
}