package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.TariffTariffOptionDataService;
import mobileoffice.dao.contracts.TariffTariffOptionRepository;
import mobileoffice.dao.entities.TariffTariffOption;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class TariffTariffOptionDataServiceImpl extends DataServiceImpl<TariffTariffOptionRepository, TariffTariffOption> implements TariffTariffOptionDataService {
public TariffTariffOptionDataServiceImpl(TariffTariffOptionRepository repository) {
    super(repository);
    }
}