package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.TariffOptionsRspDataService;
import mobileoffice.dao.contracts.TariffOptionsRspRepository;
import mobileoffice.dao.entities.TariffOptionsRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class TariffOptionsRspDataServiceImpl extends DataServiceImpl<TariffOptionsRspRepository, TariffOptionsRsp> implements TariffOptionsRspDataService {
public TariffOptionsRspDataServiceImpl(TariffOptionsRspRepository repository) {
    super(repository);
    }
}