package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.TariffOptionRspDataService;
import mobileoffice.dao.contracts.TariffOptionRspRepository;
import mobileoffice.dao.entities.TariffOptionRsp;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class TariffOptionRspDataServiceImpl extends DataServiceImpl<TariffOptionRspRepository, TariffOptionRsp> implements TariffOptionRspDataService {
public TariffOptionRspDataServiceImpl(TariffOptionRspRepository repository) {
    super(repository);
    }
}