package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.UsersDataService;
import mobileoffice.dao.contracts.UsersRepository;
import mobileoffice.dao.entities.Users;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class UsersDataServiceImpl extends DataServiceImpl<UsersRepository, Users> implements UsersDataService {
public UsersDataServiceImpl(UsersRepository repository) {
    super(repository);
    }
}