package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.VContractWithTariffDataService;
import mobileoffice.dao.contracts.VContractWithTariffRepository;
import mobileoffice.dao.entities.VContractWithTariff;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class VContractWithTariffDataServiceImpl extends DataServiceImpl<VContractWithTariffRepository, VContractWithTariff> implements VContractWithTariffDataService {
public VContractWithTariffDataServiceImpl(VContractWithTariffRepository repository) {
    super(repository);
    }
}