package mobileoffice.business.services.data;

import base.business.services.DataServiceImpl;
import mobileoffice.business.contracts.data.VTariffWithOptionsDataService;
import mobileoffice.dao.contracts.VTariffWithOptionsRepository;
import mobileoffice.dao.entities.VTariffWithOptions;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class VTariffWithOptionsDataServiceImpl extends DataServiceImpl<VTariffWithOptionsRepository, VTariffWithOptions> implements VTariffWithOptionsDataService {
public VTariffWithOptionsDataServiceImpl(VTariffWithOptionsRepository repository) {
    super(repository);
    }
}