package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class Authorities implements HasLongId, Serializable {
    public Authorities() { }
    private long id;
    private long userId;
    private String authority;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public long getUserId(){
        return this.userId;
    }

    public void setUserId (long userId) {
        this.userId = userId;
    }
    public String getAuthority(){
        return this.authority;
    }

    public void setAuthority (String authority) {
        this.authority = authority;
    }
}