package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class ContractOptionRsp implements HasLongId, Serializable {
    public ContractOptionRsp() { }
    private long id;
    private long contractId;
    private long optionId;
    private Contract contractByContractId;
    private Options optionsByOptionsId;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public long getContractId(){
        return this.contractId;
    }

    public void setContractId (long contractId) {
        this.contractId = contractId;
    }
    public long getOptionId(){
        return this.optionId;
    }

    public void setOptionId (long optionId) {
        this.optionId = optionId;
    }
    public Contract getContractByContractId(){
        return this.contractByContractId;
    }

    public void setContractByContractId (Contract contractByContractId) {
        this.contractByContractId = contractByContractId;
    }
    public Options getOptionsByOptionsId(){
        return this.optionsByOptionsId;
    }

    public void setOptionsByOptionsId (Options optionsByOptionsId) {
        this.optionsByOptionsId = optionsByOptionsId;
    }
}