package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class Manager implements HasLongId, Serializable {
    public Manager() { }
    private long id;
    private long userId;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public long getUserId(){
        return this.userId;
    }

    public void setUserId (long userId) {
        this.userId = userId;
    }
}