package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class OptionRelationsRsp implements HasLongId, Serializable {
    public OptionRelationsRsp() { }
    private long id;
    private Boolean required;
    private Boolean incompatible;
    private long optionMainId;
    private long optionSecondId;
    private Options optionsByOptionMainId;
    private Options optionsByOptionSecondId;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public Boolean getRequired(){
        return this.required;
    }

    public void setRequired (Boolean required) {
        this.required = required;
    }
    public Boolean getIncompatible(){
        return this.incompatible;
    }

    public void setIncompatible (Boolean incompatible) {
        this.incompatible = incompatible;
    }
    public long getOptionMainId(){
        return this.optionMainId;
    }

    public void setOptionMainId (long optionMainId) {
        this.optionMainId = optionMainId;
    }
    public long getOptionSecondId(){
        return this.optionSecondId;
    }

    public void setOptionSecondId (long optionSecondId) {
        this.optionSecondId = optionSecondId;
    }
    public Options getOptionsByOptionMainId(){
        return this.optionsByOptionMainId;
    }

    public void setOptionsByOptionMainId (Options optionsByOptionMainId) {
        this.optionsByOptionMainId = optionsByOptionMainId;
    }
    public Options getOptionsByOptionSecondId(){
        return this.optionsByOptionSecondId;
    }

    public void setOptionsByOptionSecondId (Options optionsByOptionSecondId) {
        this.optionsByOptionSecondId = optionsByOptionSecondId;
    }
}