package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class Options implements HasLongId, Serializable {
    public Options() { }
    private long id;
    private Float initialPrice;
    private String name;
    private Collection<ContractOptionRsp> contractOptionRspsById;
    private Collection<TariffOptionsRsp> tariffOptionsRspsById;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public Float getInitialPrice(){
        return this.initialPrice;
    }

    public void setInitialPrice (Float initialPrice) {
        this.initialPrice = initialPrice;
    }
    public String getName(){
        return this.name;
    }

    public void setName (String name) {
        this.name = name;
    }
    public Collection<ContractOptionRsp> getContractOptionRspsById(){
        return this.contractOptionRspsById;
    }

    public void setContractOptionRspsById (Collection<ContractOptionRsp> contractOptionRspsById) {
        this.contractOptionRspsById = contractOptionRspsById;
    }
    public Collection<TariffOptionsRsp> getTariffOptionsRspsById(){
        return this.tariffOptionsRspsById;
    }

    public void setTariffOptionsRspsById (Collection<TariffOptionsRsp> tariffOptionsRspsById) {
        this.tariffOptionsRspsById = tariffOptionsRspsById;
    }
}