package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class Options implements HasLongId, Serializable {
    public Options() { }
    private long id;
    private Float price;
    private Float intialPrice;
    private Collection<TariffOptionsRsp> tariffOptionsRspsById;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public Float getPrice(){
        return this.price;
    }

    public void setPrice (Float price) {
        this.price = price;
    }
    public Float getIntialPrice(){
        return this.intialPrice;
    }

    public void setIntialPrice (Float intialPrice) {
        this.intialPrice = intialPrice;
    }
    public Collection<TariffOptionsRsp> getTariffOptionsRspsById(){
        return this.tariffOptionsRspsById;
    }

    public void setTariffOptionsRspsById (Collection<TariffOptionsRsp> tariffOptionsRspsById) {
        this.tariffOptionsRspsById = tariffOptionsRspsById;
    }
}