package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class Tariff implements HasLongId, Serializable {
    public Tariff() { }
    private long id;
    private String name;
    private Float price;
    private Collection<Contract> contractsByTariffId;
    private Collection<TariffOptionsRsp> tariffOptionsRspsByTariffId;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public String getName(){
        return this.name;
    }

    public void setName (String name) {
        this.name = name;
    }
    public Float getPrice(){
        return this.price;
    }

    public void setPrice (Float price) {
        this.price = price;
    }
    public Collection<Contract> getContractsByTariffId(){
        return this.contractsByTariffId;
    }

    public void setContractsByTariffId (Collection<Contract> contractsByTariffId) {
        this.contractsByTariffId = contractsByTariffId;
    }
    public Collection<TariffOptionsRsp> getTariffOptionsRspsByTariffId(){
        return this.tariffOptionsRspsByTariffId;
    }

    public void setTariffOptionsRspsByTariffId (Collection<TariffOptionsRsp> tariffOptionsRspsByTariffId) {
        this.tariffOptionsRspsByTariffId = tariffOptionsRspsByTariffId;
    }
}