package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class TariffOptionsRsp implements HasLongId, Serializable {
    public TariffOptionsRsp() { }
    private long id;
    private long tariffId;
    private long tariffOptionId;
    private Tariff tariffByTariffId;
    private Options optionsByOptionsId;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public long getTariffId(){
        return this.tariffId;
    }

    public void setTariffId (long tariffId) {
        this.tariffId = tariffId;
    }
    public long getTariffOptionId(){
        return this.tariffOptionId;
    }

    public void setTariffOptionId (long tariffOptionId) {
        this.tariffOptionId = tariffOptionId;
    }
    public Tariff getTariffByTariffId(){
        return this.tariffByTariffId;
    }

    public void setTariffByTariffId (Tariff tariffByTariffId) {
        this.tariffByTariffId = tariffByTariffId;
    }
    public Options getOptionsByOptionsId(){
        return this.optionsByOptionsId;
    }

    public void setOptionsByOptionsId (Options optionsByOptionsId) {
        this.optionsByOptionsId = optionsByOptionsId;
    }
}