package mobileoffice.dao.entities;

import base.contracts.HasLongId;

import java.util.Collection;

/*
    !!!! AUTOGENERATED !!!!!
*/
public class TariffOptionRsp implements HasLongId {
        private long id;
        private Float price;
        private Float intialPrice;
        private Collection<TariffTariffOption> tariffTariffOptionsById;

        public long getId(){
            return this.id;
        }

        public void setId (long id) {
            this.id = id;
        }
        public Float getPrice(){
            return this.price;
        }

        public void setPrice (Float price) {
            this.price = price;
        }
        public Float getIntialPrice(){
            return this.intialPrice;
        }

        public void setIntialPrice (Float intialPrice) {
            this.intialPrice = intialPrice;
        }
        public Collection<TariffTariffOption> getTariffTariffOptionsById(){
            return this.tariffTariffOptionsById;
        }

        public void setTariffTariffOptionsById (Collection<TariffTariffOption> tariffTariffOptionsById) {
            this.tariffTariffOptionsById = tariffTariffOptionsById;
        }
}