package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class Users implements HasLongId, Serializable {
    public Users() { }
    private long id;
    private String userName;
    private String password;
    private Boolean enabled;
    private Collection<Authorities> authoritiessByUserId;
    private Collection<Client> clientsByUserId;
    private Collection<Manager> managersByUserId;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public String getUserName(){
        return this.userName;
    }

    public void setUserName (String userName) {
        this.userName = userName;
    }
    public String getPassword(){
        return this.password;
    }

    public void setPassword (String password) {
        this.password = password;
    }
    public Boolean getEnabled(){
        return this.enabled;
    }

    public void setEnabled (Boolean enabled) {
        this.enabled = enabled;
    }
    @JsonIgnore
    public Collection<Authorities> getAuthoritiessByUserId(){
        return this.authoritiessByUserId;
    }

    public void setAuthoritiessByUserId (Collection<Authorities> authoritiessByUserId) {
        this.authoritiessByUserId = authoritiessByUserId;
    }
    @JsonIgnore
    public Collection<Client> getClientsByUserId(){
        return this.clientsByUserId;
    }

    public void setClientsByUserId (Collection<Client> clientsByUserId) {
        this.clientsByUserId = clientsByUserId;
    }
    @JsonIgnore
    public Collection<Manager> getManagersByUserId(){
        return this.managersByUserId;
    }

    public void setManagersByUserId (Collection<Manager> managersByUserId) {
        this.managersByUserId = managersByUserId;
    }
}