package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class VContractWithTariff implements HasLongId, Serializable {
    public VContractWithTariff() { }
    private long id;
    private String name;
    private String number;
    private long clientId;

    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public String getName(){
        return this.name;
    }

    public void setName (String name) {
        this.name = name;
    }
    public String getNumber(){
        return this.number;
    }

    public void setNumber (String number) {
        this.number = number;
    }
    public long getClientId(){
        return this.clientId;
    }

    public void setClientId (long clientId) {
        this.clientId = clientId;
    }
}