package mobileoffice.dao.entities;

import base.dao.contracts.HasLongId;
import java.io.Serializable;

import java.util.Collection;

/*
!!!! AUTOGENERATED !!!!!
*/
public class VTariffWithOptions implements HasLongId, Serializable {
    public VTariffWithOptions() { }
    private String name;
    private long id;
    private Float price;
    private String optionName;
    private Float optionPRICE;
    private Float intialPrice;

    public String getName(){
        return this.name;
    }

    public void setName (String name) {
        this.name = name;
    }
    public long getId(){
        return this.id;
    }

    public void setId (long id) {
        this.id = id;
    }
    public Float getPrice(){
        return this.price;
    }

    public void setPrice (Float price) {
        this.price = price;
    }
    public String getOptionName(){
        return this.optionName;
    }

    public void setOptionName (String optionName) {
        this.optionName = optionName;
    }
    public Float getOptionPRICE(){
        return this.optionPRICE;
    }

    public void setOptionPRICE (Float optionPRICE) {
        this.optionPRICE = optionPRICE;
    }
    public Float getIntialPrice(){
        return this.intialPrice;
    }

    public void setIntialPrice (Float intialPrice) {
        this.intialPrice = intialPrice;
    }
}